name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Run Swift files
      # bash ignores .swift files on top-level for **/*.swift
      run: for file in **/*.swift; do swift -v $file; done;
